### ISSUE TITLE
ENH: Create pg database, insert data returned by fbo.py

### ISSUE THREAD

**Issue by csmcallister** [GSA/fbo-scraper#27]
Add module to insert data into a postgres db and perform basic queries

## Expected Behavior
- [x] Create tables
- [x] Insert data

## Context
This application will ultimately be [run as a task on cf](https://docs.cloudfoundry.org/devguide/using-tasks.html). 

Dev will require creation of a sandbox environment on cloud.gov and binding of a db service.

**Comment by csmcallister** [comment]
@austinPeel0 Met with folks to discuss and mock out an ERD for our pg database [here](https://app.sqldbm.com/SQLServer/Edit/p44365/).

Note that that ERD tool assumes a Microsoft SQL Server db, so the datatypes might be slightly different for pg. But the structure is the same.

**Comment by csmcallister** [comment]
@austinPeel0 I updated the ERD to include the new `notice_number` column in the notice table. You can find it [here](https://app.sqldbm.com/SQLServer/Share/pg55uUdlxGiGDlaKAaFui0GFrngIE8md_DYjF4jNYw0).

For each notice type, the `solnbr` key will give you the `notice_number` value.

**Comment by csmcallister** [comment]
We still need to add the action array column to the notice table. I'll get on that today.

**Comment by csmcallister** [comment]
`DataAccessLayer` in `db.py` currently creates a single session for all our db transactions. Having multiple transactions in a single session makes the transactions dependent upon one another. This can be a dangerous design pattern, so we should create a session for each transaction, thereby giving us the ability to rollback that transaction if it fails. 

@austinPeel0 once you're done with your db schema/testing logic, I can refactor the `DataAccessLayer` and all of its methods without affecting the query/insert logic you've been working on. 

First, I'll move DataAccessLayer to `db_utils.py` and convert it into a `sessionmaker` factory object:

```
class DataAccessLayer:

    def __init__(self):
        self.engine = None
        self.conn_string = 'sqlite:///:memory:'

    def connect(self):
        self.engine = create_engine(self.conn_string)
        Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)
```

Then I'll move all of the query/insert methods to `db_utils.py` and make them methods of a new class that accepts an instance of `DataAccessLayer` when initialized. This new class will contain all of our insert/query logic.

Both objects will be exportable so that we can use them whenever we want to interact with the database (e.g. in `test.py` and `fbo.py`). This will keep the configuration for how Session objects are constructed in one place. It'll also keep all our database methods separate and in one place. Finally, it will keep all of our table schemas separate, in `db.py`, which I _think_ is necessary when using a database migration tool such as [alembic](https://alembic.sqlalchemy.org/en/latest/tutorial.html).

**Comment by austinPeel0** [comment]
It will only create a single session if you are using the same object. 

DataAccessLayer().add_json_nightly_file_to_postgres()
DataAccessLayer().add_model_data()

creates separate objects and have separate sessions. 

I get moving the DataAccessLayer to utils which makes sense.

**Comment by austinPeel0** [comment]
We should be closing out of the sessions too, which seems like an issue if the application needs to scale

**Comment by csmcallister** [comment]
Agreed. This snippet from the docs seems applicable. It tries to keep the details of session, transaction and exception management as far as possible from the details of the program doing its work.

```
from contextlib import contextmanager

@contextmanager
def session_scope(dal):   #an instance of our DataAccessLayer would be passed in as an arg
    """Provide a transactional scope around a series of operations."""
    session = dal.Session() #we use our dal instance it to create a session
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()


def run_my_program():
    with session_scope() as session:
        ThingOne().go(session)
        ThingTwo().go(session)
```

**Comment by csmcallister** [comment]
So I think we're going to need to create a User table in our database so that we can map users to actions.
